db.url=jdbc:sqlserver://localhost:1433;databaseName=FWatch;encrypt=true;trustServerCertificate=true
db.username=sa
db.password=123456
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
upload.product.path=uploads/products
