# Google OAuth Credentials. Replace these with your actual credentials from Google Cloud Console.
smarttick.google.clientId=919236569303-e5rufmj8cn99sbh0sejvtlna1n0b410f.apps.googleusercontent.com
smarttick.google.clientSecret=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
smarttick.google.redirectUri=http://localhost:8080/SMARTTICK/GoogleLogin
