<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Add Watch | SMARTTICK Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/smarttick.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin-ops.css?v=20260725-ops6"></head><body class="admin-ops-page"><div class="dashboard-shell"><jsp:include page="SidebarDashboard.jsp"/><main class="dash-main"><div class="section-head"><div><h2>Add Watch Product</h2><p class="section-sub">Main image is required; JPG, PNG, or WEBP only, up to 5 MB per image.</p></div><a class="btn btn-outline" href="${pageContext.request.contextPath}/ProductListServlet">Back</a></div><c:if test="${not empty errorMsg}"><div class="alert alert-danger"><c:out value="${errorMsg}"/></div></c:if>
<form class="panel" action="${pageContext.request.contextPath}/CreateProductServlet" method="post" enctype="multipart/form-data"><div class="form-two"><label>Category<select class="form-select" name="categoryName" required onchange="location.href='${pageContext.request.contextPath}/CreateProductServlet?name='+encodeURIComponent(this.value)"><option value="">Select Category</option><c:forEach items="${categories}" var="c"><option value="${c}" ${categoryName==c?'selected':''}><c:out value="${c}"/></option></c:forEach></select></label><label>Brand<select class="form-select" name="brandName" required><option value="">Select Brand</option><c:forEach items="${brands}" var="b"><option value="${b}"><c:out value="${b}"/></option></c:forEach></select></label><label>Model<input class="form-control" name="model" maxlength="100" required></label><label>Full Name<input class="form-control" name="fullName" maxlength="255" required></label><label>Sale Price (VND)<input class="form-control" type="number" name="price" min="1" required></label><label>Stock<input class="form-control" type="number" name="stock" min="0" required></label><label>Status<select class="form-select" name="isDeleted"><option value="0">On Sale</option><option value="1">Hidden</option></select></label></div><label>Description<textarea name="description" rows="5" required></textarea></label>
<div class="form-two"><label>Main image<input class="form-control image-input smart-file-input" type="file" name="txtP1" accept="image/jpeg,image/png,image/webp" required></label><label>Additional image 1<input class="form-control image-input smart-file-input" type="file" name="txtP2" accept="image/jpeg,image/png,image/webp"></label><label>Additional image 2<input class="form-control image-input smart-file-input" type="file" name="txtP3" accept="image/jpeg,image/png,image/webp"></label><label>Additional image 3<input class="form-control image-input smart-file-input" type="file" name="txtP4" accept="image/jpeg,image/png,image/webp"></label></div><div id="imagePreview" class="thumbs"></div>
<c:if test="${not empty attributes}"><h3>Specifications</h3><div class="form-two"><c:forEach items="${attributes}" var="a"><label><c:out value="${a.attributeName}"/><input type="hidden" name="attributeId" value="${a.attributeId}"><input class="form-control" name="attributeInfor_${a.attributeId}" required></label></c:forEach></div></c:if><button class="btn btn-primary" type="submit">Save Product</button></form></main></div><script>document.querySelectorAll('.image-input').forEach(i=>i.addEventListener('change',()=>{const p=document.getElementById('imagePreview');p.innerHTML='';document.querySelectorAll('.image-input').forEach(f=>{if(f.files[0]){const img=document.createElement('img');img.src=URL.createObjectURL(f.files[0]);p.appendChild(img)}})}));</script><script src="${pageContext.request.contextPath}/assets/js/file-input.js"></script></body></html>




