<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><c:out value="${product.fullName}"/> | SMARTTICK</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/smarttick.css"></head><body><jsp:include page="header.jsp" />
<main class="container"><section class="detail"><div><div class="gallery-main"><img id="mainWatchImage" src="${pageContext.request.contextPath}/product-images/${product.image}" onerror="this.src='${pageContext.request.contextPath}/assets/imgs/Products/watches/watch-placeholder.svg'" alt="SMARTTICK watch image"></div><div class="thumbs"><c:if test="${not empty product.image}"><img src="${pageContext.request.contextPath}/product-images/${product.image}" onclick="document.getElementById('mainWatchImage').src=this.src" alt="Main image"></c:if><c:if test="${not empty product.image1}"><img src="${pageContext.request.contextPath}/product-images/${product.image1}" onclick="document.getElementById('mainWatchImage').src=this.src" alt="Additional image"></c:if><c:if test="${not empty product.image2}"><img src="${pageContext.request.contextPath}/product-images/${product.image2}" onclick="document.getElementById('mainWatchImage').src=this.src" alt="Additional image"></c:if><c:if test="${not empty product.image3}"><img src="${pageContext.request.contextPath}/product-images/${product.image3}" onclick="document.getElementById('mainWatchImage').src=this.src" alt="Additional image"></c:if></div></div>
<div><span class="eyebrow"><c:out value="${product.brandName}"/></span><h1><c:out value="${product.fullName}"/></h1><div class="model">Model: <c:out value="${product.model}"/> · <c:out value="${product.categoryName}"/></div><div class="detail-price"><fmt:formatNumber value="${product.price}" pattern="#,##0"/> VND</div><p style="line-height:1.8;color:var(--muted)"><c:out value="${product.description}"/></p><p class="stock ${product.stock <= 0 ? 'out' : ''}"><c:choose><c:when test="${product.stock > 0}">In Stock: ${product.stock}</c:when><c:otherwise>Temporarily Out of Stock</c:otherwise></c:choose></p><div class="card-actions" style="max-width:420px"><c:if test="${product.stock > 0}"><a class="btn btn-primary" href="${pageContext.request.contextPath}/AddToCart?id=${product.productId}">Add to Cart</a></c:if><a class="btn btn-outline" href="${pageContext.request.contextPath}/Watches">Continue Shopping</a></div>
<div class="specs"><div class="spec-row"><strong>Brand</strong><span><c:out value="${product.brandName}"/></span></div><div class="spec-row"><strong>Category</strong><span><c:out value="${product.categoryName}"/></span></div><c:forEach items="${attributes}" var="a"><div class="spec-row"><strong><c:out value="${a.attributeName}"/></strong><span><c:out value="${a.attributeInfor}"/></span></div></c:forEach></div></div></section>
<section class="section alt" style="padding-left:24px;padding-right:24px;border-radius:18px;margin-bottom:60px"><div class="section-head"><div><h2>Product Reviews</h2><p class="section-sub">Average rating: ${star}/5</p></div></div><c:if test="${isOk}"><form method="post" action="${pageContext.request.contextPath}/ProductDetailServlet" class="panel"><input type="hidden" name="productId" value="${product.productId}"><label>Rating</label><select class="form-select" name="star" required><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><label style="display:block;margin-top:12px">Review</label><textarea name="comment" rows="4" required></textarea><button class="btn btn-primary" type="submit" style="margin-top:12px">Submit Review</button></form></c:if><c:forEach items="${dataRating}" var="r"><article class="panel"><strong><c:out value="${r.fullName}"/></strong><span> · ${r.star}/5</span><p><c:out value="${r.comment}"/></p><small>${r.createdDate}</small><c:forEach items="${dataReplies}" var="reply"><c:if test="${reply.rateID == r.rateID}"><div class="alert alert-success"><strong>SMARTTICK reply:</strong> <c:out value="${reply.answer}"/></div></c:if></c:forEach></article></c:forEach></section>
</main><jsp:include page="footer.jsp" /></body></html>
