<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Update Watch | SMARTTICK Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/smarttick.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin-ops.css?v=20260725-ops6"></head><body class="admin-ops-page"><div class="dashboard-shell"><jsp:include page="SidebarDashboard.jsp"/><main class="dash-main"><div class="section-head"><div><h2>Update Product</h2><p class="section-sub"><c:out value="${product.fullName}"/></p></div><a class="btn btn-outline" href="${pageContext.request.contextPath}/ProductListServlet">Back</a></div><c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<form class="panel" action="${pageContext.request.contextPath}/UpdateProductServlet" method="post" enctype="multipart/form-data"><input type="hidden" name="id" value="${product.productId}"><div class="form-two"><label>Category<select class="form-select" name="categoryName" required><c:forEach items="${categories}" var="c"><option value="${c}" ${product.categoryName==c?'selected':''}><c:out value="${c}"/></option></c:forEach></select></label><label>Brand<select class="form-select" name="brandName" required><c:forEach items="${brands}" var="b"><option value="${b}" ${product.brandName==b?'selected':''}><c:out value="${b}"/></option></c:forEach></select></label><label>Model<input class="form-control" name="model" value="<c:out value='${product.model}'/>" required></label><label>Full Name<input class="form-control" name="fullName" value="<c:out value='${product.fullName}'/>" required></label><label>Sale Price (VND)<input class="form-control" type="number" name="price" min="1" value="${product.price}" required></label><label>Stock<input class="form-control" type="number" name="stock" min="0" value="${product.stock}" required></label><label>Status<select class="form-select" name="isDeleted"><option value="0" ${product.deleted==0?'selected':''}>On Sale</option><option value="1" ${product.deleted==1?'selected':''}>Hidden</option></select></label></div><label>Description<textarea name="description" rows="5" required><c:out value="${product.description}"/></textarea></label>
<h3>Current Images / Replace Images</h3><div class="form-two"><label>Main image<c:if test="${not empty product.image}"><img class="form-image" src="${pageContext.request.contextPath}/product-images/${product.image}"></c:if><input class="form-control smart-file-input" type="file" name="txtPPic" accept="image/jpeg,image/png,image/webp"></label><label>Additional image 1<c:if test="${not empty product.image1}"><img class="form-image" src="${pageContext.request.contextPath}/product-images/${product.image1}"></c:if><input class="form-control smart-file-input" type="file" name="txtPPic1" accept="image/jpeg,image/png,image/webp"></label><label>Additional image 2<c:if test="${not empty product.image2}"><img class="form-image" src="${pageContext.request.contextPath}/product-images/${product.image2}"></c:if><input class="form-control smart-file-input" type="file" name="txtPPic2" accept="image/jpeg,image/png,image/webp"></label><label>Additional image 3<c:if test="${not empty product.image3}"><img class="form-image" src="${pageContext.request.contextPath}/product-images/${product.image3}"></c:if><input class="form-control smart-file-input" type="file" name="txtPPic3" accept="image/jpeg,image/png,image/webp"></label></div>
<c:if test="${not empty attributes}"><h3>Specifications</h3><div class="form-two"><c:forEach items="${attributes}" var="a"><label><c:out value="${a.attributeName}"/><input type="hidden" name="attributeId" value="${a.attributeId}"><input class="form-control" name="attributeInfor_${a.attributeId}" value="${product.attributes[a.attributeName]}" required></label></c:forEach></div></c:if><button class="btn btn-primary" type="submit">Update Product</button></form></main></div><script src="${pageContext.request.contextPath}/assets/js/file-input.js"></script></body></html>




